# Generated by Django 5.0.3 on 2024-05-26 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_lecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=254)),
                ('note', models.CharField(max_length=5000)),
            ],
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='lecture',
            name='teacher',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lecture',
            name='theme',
            field=models.CharField(max_length=250),
        ),
    ]
